Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 4192]
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/site.yml"
    ansible.galaxy_role_file = "ansible/requirements.yml"
    ansible.raw_arguments = [
       "--module-path", "./ansible/roles/ansible-role-girder/library"
    ]
  end
end
